### ISSUE TITLE
Add New Config Value

### ISSUE THREAD

**Issue by mrgoodbytes8667** [mrgoodbytes8667/response-bundle#20]
Need to add equivalent config for mrgoodbytes8667/twitch-client-bundle#15:

```yaml
bytes_twitch_client:
    eventsub_callback:
      add_type: false
```

```php
// ...
->arrayNode('eventsub_callback')
    // ...
        ->booleanNode('add_type')
            ->info('Add the type parameter?')
            ->defaultTrue()
        ->end()
// ...
```
